# Test script that attempts to trigger an "Excess Flood" quit.
# Part of the VirginiaBot/PuppyBot/SmokeBot toolset.
# Changelog
# 0.03 - upped to 75 messages.
# 0.02 - removed restart trigger.
# 0.01 - initial version.

bind pub - !excessfloodtest excessfloodtest

proc excessfloodtest {nick host hand chan args} {
putlog "ALERT: EXCESS FLOOD TEST TRIGGERED!"
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "Sending..."
putnow "PRIVMSG #VASirens :Triggering excess flood."
putlog "75 messages sent."
}
